// Posts constants
export const START_FETCHING_POSTS = 'START_FETCHING_POSTS';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FINISH_FETCHING_POSTS = 'FINISH_FETCHING_POSTS';
export const POST_UPLOAD_PROGRESS = 'POST_UPLOAD_PROGRESS';
export const CLEAR_UPLOAD_PROGRESS = 'CLEAR_UPLOAD_PROGRESS';
export const REQUESTED_USER_POSTS = 'REQUESTED_USER_POSTS';
export const REQUESTED_SAVED_POSTS = 'REQUESTED_SAVED_POSTS';
export const GET_REQUESTED_POST = 'GET_REQUESTED_POST';
export const SET_LOADING = 'SET_LOADING';
export const REMOVE_LOADING = 'REMOVE_LOADING';

// auth actions
export const STARTS_TO_LOADING = 'STARTS_TO_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ACTION_ERROR = 'AUTH_ACTION_ERROR';
export const GET_LOGGED_IN_USER = 'GET_LOGGED_IN_USER';
export const GET_REQUESTED_USER = 'GET_REQUESTED_USER';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const END_LOADING = 'END_LOADING';
export const START_TO_UPLOAD_PROFILE_PHOTO = 'START_TO_UPLOAD_PROFILE_PHOTO';
export const ENDS_TO_UPLOAD_PROFILE_PHOTO = 'ENDS_TO_UPLOAD_PROFILE_PHOTO';
export const GET_FOLLOWERS = 'GET_FOLLOWERS';
export const GET_FOLLOWING= 'GET_FOLLOWING';
export const GET_FOLLOWERS_FOR_LOGGED_IN = 'GET_FOLLOWERS_FOR_LOGGED_IN';
export const GET_FOLLOWING_FOR_LOGGED_IN= 'GET_FOLLOWING_FOR_LOGGED_IN';
export const LOGGED_IN_LOADING = 'LOGGED_IN_LOADING';
export const END_LOGGED_LOADING = 'END_LOGGED_LOADING';
export const GET_ALL_USERS = 'GET_ALL_USERS';